remote_theme: jekyll/minima
minima:
  skin: dark
title: Networking stuff
#author:
#  name: tomas
description: >
  Anything networking-related, from concepts to my own learnings



# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
header_pages:
  - about.md

  social_links:
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/tomas-pro%C5%A1kus-768280139/" }
