remote_theme: jekyll/minima
title: Networking stuff
#author:
#  name: tomas
description:
  Anything networking-related, from concepts to my own learnings

minima:
  skin: dark


# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
header_pages:
  - about.md
